export const TYPES = {
    IGetAllUsersUseCase: "IGetAllUsersUseCase",
    IUserLoginUseCase: "IUserLoginUseCase",
    IUserRepository: "IUserRepository",
    IRefreshTokenRepository: "IRefreshTokenRepository",
    IServicesTypeRepository: "IServicesTypeRepository",
    IGenerateRefreshTokenUseCase: "IGenerateRefreshTokenUseCase",
    IRefreshTokenUseCase: "IRefreshTokenUseCase",
    IGetUsersUseCase: "IGetUsersUseCase",
    ICreateUserUseCase: "ICreateUserUseCase",
    IUpdateUserUseCase: "IUpdateUserUseCase",
    IDeleteUserUseCase: "IDeleteUserUseCase",
    IGetUserByIdUseCase: "IGetUserByIdUseCase",
    IGetServicesTypeUseCase: "IGetServicesTypeUseCase",
    ICreateServicesTypeUseCase: "ICreateServicesTypeUseCase",
    IDeleteServiceTypeUseCase: "IDeleteServiceTypeUseCase",
};